appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: CxKrV6mXP47zRb3fN3J7htwGmcS2S0N6Lap6shqnsdg8vmRs7RL321OnooNSDDTByTy72hsOEA4EEdclaf61cD6zlcq6BdYpTJJqvbNVBO2GAZUW0G3PxaUl3vZyseUqlwJCZ2pz8fMk8pedWht3dAy4/CLQY2eUbs4D8rJFn8gaSWM3ibkAskK+4TYUqlhmaHh+ubJY4fBWwUqiL4b8OuU8wU8n05KAqqEbfAXLoasK+6NTkkI+jhRZ9fBMlUelIRn2/T0n3SV9q4x3gq0PzPpUvE9K+ZR8Ngo6UxHbTDgesUpnybEjvHlpHAT53yrQOssIj2X2F5hFbuYcO+z/FC/nh6njyqe4ibLNm6wfKi+tlKBKcA/gJIX2NA+1MvCN95oYGQLVAp5BixHibyc+O1WEpCyY8NCBpYrXq+ja4ewBw3PrV0wAAh54HxHILIYl0/4qgsIzVScgV0kK3m1EgMFF4Y4E9WObmuMKZjurRJwxbZX/L/zacmKnc8+NDuetEXzYZtvj8S6P6r8YSME9YOCm1u4xiBDKsW+o1fkqIp73M3BIORprtm8ciUJzT1zIXY2+EyM1OjJgVFb/mcYbmIZR2u3s7RZJRGSFEw2+5tvodFMwyIiXea8M9O079dj5i0jOpoUv9LRkscrw3PTQslTWQKj29AAXC5CDbdAn1q0=
